(()=>{
'use strict';
const SCALE_KEY='wwmsync:vision-scale',ROI_KEY='wwmsync:vision-roi',ORIENTATION_KEY='wwmsync:vision-orientation';
const SAMPLE_MS=250,WORK=192,MIN_MARKER_PX=.05,TRACKING_REFERENCE_ZOOM=11;
const ZERO_RAW_EPSILON=0.05,ZERO_CUMULATIVE_EPSILON=0.25;
const STATUS=Object.freeze({TRACKING:'TRACKING',LOW_CONFIDENCE:'LOW_CONFIDENCE',PAUSED_NO_FRAME:'PAUSED_NO_FRAME',NEEDS_RESEED:'NEEDS_RESEED'});
const TEXT={
vi:{title:'Vision Sync',intro:'Chia sẻ cửa sổ GeForce NOW hoặc WWM local client. WWMSync chỉ đọc pixel minimap cục bộ trong tab này; không upload video và không đọc memory/process/file/packet.',start:'Bắt đầu Vision Sync',stop:'Dừng',roiHint:'ROI mặc định ở minimap góc trên-trái. Bấm đúng tâm minimap trong preview nếu cần chỉnh.',anchor:'Đặt vị trí hiện tại',resync:'Đồng bộ lại vị trí',anchorHint:'Bấm nút rồi click đúng vị trí nhân vật hiện tại trên WWMSync map. Vị trí này là mốc tuyệt đối duy nhất; sau đó marker chỉ di chuyển tương đối theo minimap.',confidence:'Tin cậy',accepted:'Frame làm marker di chuyển',held:'Frame giữ',advanced:'Tinh chỉnh',roiSize:'Kích thước ROI',scale:'Tỉ lệ di chuyển',orientation:'Bù hướng minimap',diagnostics:'Motion diagnostics',rawDelta:'Raw terrain dx/dy',correctedDelta:'Converted map dx/dy',cumulative:'Cumulative displacement',markerDelta:'Marker Δ lat/lng',diagConfidence:'Confidence',holdReason:'Tracking state',off:'Vision Sync đang tắt. Vị trí cuối cùng được giữ lại.',ready:'Capture đã sẵn sàng. Hãy đặt vị trí hiện tại trên map để bắt đầu tracking.',clickMap:'Click vị trí hiện tại của nhân vật trên map.',tracking:'Tracking tương đối từ vị trí đã đặt.',lowConfidence:'Frame hiện tại có độ tin cậy thấp; marker được giữ nguyên.',paused:'Không có frame capture; marker giữ nguyên vị trí cuối.',needsReseed:'Cần đặt lại vị trí hiện tại trước khi tiếp tục tracking.',anchorSet:'Đã đặt vị trí. Frame minimap tiếp theo sẽ là baseline mới.',roiSelected:'Đã cập nhật vùng minimap; frame tiếp theo sẽ là baseline mới.'},
en:{title:'Vision Sync',intro:'Share either GeForce NOW or the local WWM client. WWMSync reads minimap pixels locally in this tab only; it does not upload video or read memory/process/files/packets.',start:'Start Vision Sync',stop:'Stop',roiHint:'The default ROI targets the upper-left minimap. Click the minimap center in the preview if needed.',anchor:'Set current position',resync:'Re-sync position',anchorHint:'Click the button, then click your actual player position on the WWMSync map. That manual seed is the only absolute position; subsequent marker updates are relative minimap motion only.',confidence:'Confidence',accepted:'Frames moving marker',held:'Held frames',advanced:'Tuning',roiSize:'ROI size',scale:'Movement scale',orientation:'Minimap orientation',diagnostics:'Motion diagnostics',rawDelta:'Raw terrain dx/dy',correctedDelta:'Converted map dx/dy',cumulative:'Cumulative displacement',markerDelta:'Marker Δ lat/lng',diagConfidence:'Confidence',holdReason:'Tracking state',off:'Vision Sync is off. The last marker position is retained.',ready:'Capture is ready. Set your current map position to begin tracking.',clickMap:'Click your current character position on the map.',tracking:'Tracking relative motion from the manual seed.',lowConfidence:'Current frame confidence is low; marker position is held.',paused:'No capture frame is available; the last marker position is held.',needsReseed:'Set your current position again before tracking can continue.',anchorSet:'Position set. The next minimap frame becomes the new baseline.',roiSelected:'Minimap region updated; the next frame becomes the new baseline.'}
};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const loadNumber=(key,fallback,min,max)=>{const raw=localStorage.getItem(key);if(raw===null||raw==='')return fallback;const v=Number(raw);return Number.isFinite(v)?clamp(v,min,max):fallback};
const freshTracking=()=>({currentMapX:null,currentMapY:null,cumulativeDx:0,cumulativeDy:0,confidence:0,frameCount:0,status:STATUS.PAUSED_NO_FRAME});
const state={stream:null,video:null,previewRaf:0,timer:0,workCanvas:null,workCtx:null,roiX:null,roiY:null,roiFraction:loadNumber(ROI_KEY,.25,.12,.34),scale:loadNumber(SCALE_KEY,1,.25,6),orientation:loadNumber(ORIENTATION_KEY,0,-180,180),previous:null,manualSeed:null,trackingState:freshTracking(),marker:null,mapClickHandler:null,accepted:0,held:0,lowFrames:0,rawDx:0,rawDy:0,correctedDx:0,correctedDy:0,markerDeltaLat:0,markerDeltaLng:0,holdReason:'—',lastScore:0,lastEnergy:0,statusKey:'off',testReplayStream:false};
let mapRef=null;
const ids=['visionStartButton','visionStopButton','visionAnchorButton','visionBadge','visionStatus','visionPreview','visionSetup','visionConfidence','visionAccepted','visionHeld','visionRoiSize','visionRoiValue','visionScale','visionScaleValue','visionOrientation','visionOrientationValue','visionRawDelta','visionCorrectedDelta','visionCumulative','visionMarkerDelta','visionDiagnosticConfidence','visionHoldReason','sidebar'];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const lang=()=>document.documentElement.lang==='en'||document.getElementById('languageSelect')?.value==='en'?'en':'vi',tx=key=>TEXT[lang()][key]||TEXT.en[key]||key,fmt=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(3)}`:'—';
function statusClass(status){return status===STATUS.TRACKING?'good':status===STATUS.LOW_CONFIDENCE||status===STATUS.NEEDS_RESEED?'warn':''}
function statusLabel(status){return status===STATUS.PAUSED_NO_FRAME?'PAUSED':status}
function setStatus(status,key){state.trackingState.status=status;state.statusKey=key;if(!el.visionBadge||!el.visionStatus)return;el.visionBadge.textContent=statusLabel(status);el.visionBadge.className=`status-badge ${statusClass(status)}`.trim();el.visionStatus.textContent=tx(key);el.visionStatus.className=`vision-status ${statusClass(status)}`.trim()}
function refreshAnchorLabel(){if(el.visionAnchorButton)el.visionAnchorButton.textContent=tx(state.manualSeed?'resync':'anchor')}
function metrics(){if(el.visionConfidence)el.visionConfidence.textContent=`${Math.round(clamp(state.trackingState.confidence,0,1)*100)}%`;if(el.visionAccepted)el.visionAccepted.textContent=String(state.accepted);if(el.visionHeld)el.visionHeld.textContent=String(state.held);if(el.visionRoiValue)el.visionRoiValue.textContent=`${Math.round(state.roiFraction*100)}%`;if(el.visionScaleValue)el.visionScaleValue.textContent=`${state.scale.toFixed(2)}×`;if(el.visionOrientationValue)el.visionOrientationValue.textContent=`${Math.round(state.orientation)}°`;if(el.visionRawDelta)el.visionRawDelta.textContent=`${fmt(state.rawDx)}, ${fmt(state.rawDy)} work px`;if(el.visionCorrectedDelta)el.visionCorrectedDelta.textContent=`${fmt(state.correctedDx)}, ${fmt(state.correctedDy)} map px`;if(el.visionCumulative)el.visionCumulative.textContent=`${fmt(state.trackingState.cumulativeDx)}, ${fmt(state.trackingState.cumulativeDy)} map px`;if(el.visionMarkerDelta)el.visionMarkerDelta.textContent=`${fmt(state.markerDeltaLat)}, ${fmt(state.markerDeltaLng)}`;if(el.visionDiagnosticConfidence)el.visionDiagnosticConfidence.textContent=`${Math.round(clamp(state.trackingState.confidence,0,1)*100)}% · corr ${state.lastScore.toFixed(3)} · energy ${state.lastEnergy.toFixed(2)}`;if(el.visionHoldReason)el.visionHoldReason.textContent=`${state.trackingState.status} · ${state.holdReason||'—'}`}
function localize(){document.querySelectorAll('[data-vision-i18n]').forEach(node=>{const key=node.dataset.visionI18n;if(key==='anchor')refreshAnchorLabel();else node.textContent=tx(key)});setStatus(state.trackingState.status,state.statusKey);refreshAnchorLabel();metrics()}
function refresh(){const active=!!state.stream;el.visionStartButton.disabled=active;el.visionStopButton.disabled=!active;el.visionAnchorButton.disabled=!active||!mapRef;el.visionSetup.classList.toggle('hidden',!active);el.visionRoiSize.value=String(state.roiFraction);el.visionScale.value=String(state.scale);if(el.visionOrientation)el.visionOrientation.value=String(state.orientation);refreshAnchorLabel();metrics()}
function clearMapClick(){if(state.mapClickHandler&&mapRef)mapRef.off('click',state.mapClickHandler);state.mapClickHandler=null;el.visionAnchorButton.classList.remove('armed')}
function resetMotionDiagnostics(reason='—'){state.rawDx=0;state.rawDy=0;state.correctedDx=0;state.correctedDy=0;state.markerDeltaLat=0;state.markerDeltaLng=0;state.holdReason=reason;state.lastScore=0;state.lastEnergy=0}
function clearSeed(reason='needs-reseed'){clearMapClick();if(state.marker){state.marker.remove();state.marker=null}state.manualSeed=null;state.previous=null;state.accepted=0;state.held=0;state.lowFrames=0;state.trackingState=freshTracking();resetMotionDiagnostics(reason);setStatus(state.stream?STATUS.NEEDS_RESEED:STATUS.PAUSED_NO_FRAME,state.stream?'needsReseed':'paused');refresh()}
function attachMap(map){mapRef=map;map.once('unload',()=>{if(mapRef===map){if(state.marker){state.marker.remove();state.marker=null}state.manualSeed=null;state.previous=null;state.trackingState=freshTracking();mapRef=null;setStatus(state.stream?STATUS.NEEDS_RESEED:STATUS.PAUSED_NO_FRAME,state.stream?'needsReseed':'paused');refresh();window.dispatchEvent(new CustomEvent('wwmsync:vision:map-unloaded'))}});refresh();window.dispatchEvent(new CustomEvent('wwmsync:vision:map-ready'))}
if(window.L?.map){const original=window.L.map;window.L.map=function(...args){const map=original.apply(this,args);attachMap(map);return map}}
function markerAt(latlng){if(!mapRef)return false;if(state.marker)state.marker.setLatLng(latlng);else{const icon=window.L.divIcon({className:'vision-player-marker-wrap',html:'<div class="vision-player-marker"><span></span></div>',iconSize:[24,24],iconAnchor:[12,12]});state.marker=window.L.marker(latlng,{icon,interactive:false,zIndexOffset:1200}).addTo(mapRef)}return true}
function setManualSeed(latlng,timestamp=Date.now()){if(!mapRef)return{ok:false,reason:'map-unavailable'};const ll=window.L.latLng(Number(latlng.lat),Number(latlng.lng)),bounds=mapRef.options.maxBounds;if(!Number.isFinite(ll.lat)||!Number.isFinite(ll.lng))return{ok:false,reason:'invalid-latlng'};if(bounds&&!bounds.contains(ll))return{ok:false,reason:'out-of-map-bounds'};const p=mapRef.project(ll,TRACKING_REFERENCE_ZOOM);state.manualSeed={mapX:p.x,mapY:p.y,timestamp:Number(timestamp)||Date.now()};state.trackingState={currentMapX:p.x,currentMapY:p.y,cumulativeDx:0,cumulativeDy:0,confidence:0,frameCount:0,status:state.stream?STATUS.TRACKING:STATUS.PAUSED_NO_FRAME};state.previous=null;state.accepted=0;state.held=0;state.lowFrames=0;resetMotionDiagnostics('manual-seed');markerAt(ll);setStatus(state.trackingState.status,state.stream?'anchorSet':'paused');refresh();const detail={manualSeed:{...state.manualSeed},lat:ll.lat,lng:ll.lng};window.dispatchEvent(new CustomEvent('wwmsync:vision:manual-seed',{detail}));return{ok:true,...detail}}
function requestSeed(){if(!state.stream||!mapRef)return;clearMapClick();el.visionAnchorButton.classList.add('armed');setStatus(STATUS.NEEDS_RESEED,'clickMap');if(innerWidth<=800)el.sidebar?.classList.remove('open');const map=mapRef,handler=event=>{map.off('click',handler);state.mapClickHandler=null;el.visionAnchorButton.classList.remove('armed');const result=setManualSeed(event.latlng);if(!result.ok)setStatus(STATUS.NEEDS_RESEED,'needsReseed')};state.mapClickHandler=handler;map.on('click',handler)}
function roi(video){const unit=Math.min(video.videoWidth,video.videoHeight),size=unit*state.roiFraction,half=size/2,defaultCenter=unit*.125,cx=clamp(state.roiX??defaultCenter,half,video.videoWidth-half),cy=clamp(state.roiY??defaultCenter,half,video.videoHeight-half);state.roiX=cx;state.roiY=cy;return{x:cx-half,y:cy-half,size}}
function preview(){const video=state.video,canvas=el.visionPreview;if(!video||!state.stream)return;const width=360,height=Math.max(160,Math.round(width*video.videoHeight/video.videoWidth));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}const ctx=canvas.getContext('2d',{alpha:false});ctx.drawImage(video,0,0,width,height);const r=roi(video),sx=width/video.videoWidth,sy=height/video.videoHeight;ctx.save();ctx.strokeStyle='#f2cc7a';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.strokeRect(r.x*sx,r.y*sy,r.size*sx,r.size*sy);ctx.restore();state.previewRaf=requestAnimationFrame(preview)}
function announceRoiChange(reason){state.previous=null;state.lowFrames=0;state.holdReason=reason;state.markerDeltaLat=0;state.markerDeltaLng=0;if(state.manualSeed)setStatus(state.stream?STATUS.TRACKING:STATUS.PAUSED_NO_FRAME,state.stream?'roiSelected':'paused');else setStatus(state.stream?STATUS.NEEDS_RESEED:STATUS.PAUSED_NO_FRAME,state.stream?'needsReseed':'paused');window.dispatchEvent(new CustomEvent('wwmsync:vision:roi-ready',{detail:{reason}}));metrics()}
function selectRoi(event){if(!state.video||!state.stream)return;const rect=el.visionPreview.getBoundingClientRect();state.roiX=clamp((event.clientX-rect.left)/rect.width,0,1)*state.video.videoWidth;state.roiY=clamp((event.clientY-rect.top)/rect.height,0,1)*state.video.videoHeight;announceRoiChange('roi-baseline-reset')}
function visionPercentile(values,p){if(!values.length)return 0;const a=Array.from(values).sort((x,y)=>x-y);return a[Math.min(a.length-1,Math.max(0,Math.floor((a.length-1)*p)))]}
function visionGaussianBlur(gray,n){const weights=[.027630550638898826,.0662822452863612,.1238315368057753,.18017382291138087,.20416368871516755,.18017382291138087,.1238315368057753,.0662822452863612,.027630550638898826],tmp=new Float32Array(gray.length),out=new Float32Array(gray.length);for(let y=0;y<n;y++)for(let x=0;x<n;x++){let sum=0;for(let k=-4;k<=4;k++)sum+=gray[y*n+clamp(x+k,0,n-1)]*weights[k+4];tmp[y*n+x]=sum}for(let y=0;y<n;y++)for(let x=0;x<n;x++){let sum=0;for(let k=-4;k<=4;k++)sum+=tmp[clamp(y+k,0,n-1)*n+x]*weights[k+4];out[y*n+x]=sum}return out}
function featureFromWorkCanvas(sourceScale){const ctx=state.workCtx,n=WORK,rgba=ctx.getImageData(0,0,n,n).data,gray=new Float32Array(n*n),sample=[],feature=new Float32Array(n*n),rawData=new Float32Array(n*n),c=(n-1)/2,inner2=(n*.13)**2,outer2=(n*.43)**2;for(let i=0,p=0;i<gray.length;i++,p+=4)gray[i]=rgba[p]*.299+rgba[p+1]*.587+rgba[p+2]*.114;for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const rx=x-c,ry=y-c,r2=rx*rx+ry*ry;if(r2>=inner2&&r2<=outer2)sample.push(gray[y*n+x])}const threshold=clamp(visionPercentile(sample,.96),150,195),signal=new Float32Array(n*n);for(let i=0;i<signal.length;i++)signal[i]=clamp((gray[i]-threshold)/25,0,1)*255;const stable=visionGaussianBlur(signal,n);let energy=0,rawEnergy=0,count=0;for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const rx=x-c,ry=y-c,r2=rx*rx+ry*ry;if(r2<inner2||r2>outer2)continue;const i=y*n+x,gx=stable[i+1]-stable[i-1],gy=stable[i+n]-stable[i-n],v=gx+gy*.7,rgx=gray[i+1]-gray[i-1],rgy=gray[i+n]-gray[i-n],rv=rgx+rgy*.7;feature[i]=v;rawData[i]=rv;energy+=v*v;rawEnergy+=rv*rv;count++}return{data:feature,energy:count?Math.sqrt(energy/count):0,rawData,rawEnergy:count?Math.sqrt(rawEnergy/count):0,sourceScale,normalization:{kind:'dual-source-agnostic',threshold}}}
function ensureWorkCanvas(){if(!state.workCanvas){state.workCanvas=document.createElement('canvas');state.workCanvas.width=WORK;state.workCanvas.height=WORK;state.workCtx=state.workCanvas.getContext('2d',{willReadFrequently:true})}}
function featuresFromCanvas(canvas){if(!(canvas instanceof HTMLCanvasElement))return null;ensureWorkCanvas();const ctx=state.workCtx,n=WORK;ctx.clearRect(0,0,n,n);ctx.drawImage(canvas,0,0,canvas.width,canvas.height,0,0,n,n);return featureFromWorkCanvas(canvas.width/n)}
function features(){const video=state.video;if(!video?.videoWidth)return null;ensureWorkCanvas();const r=roi(video),ctx=state.workCtx,n=WORK;ctx.clearRect(0,0,n,n);ctx.drawImage(video,r.x,r.y,r.size,r.size,0,0,n,n);return featureFromWorkCanvas(r.size/n)}
function correlation(a,b,n,dx,dy){const c=(n-1)/2,inner2=(n*.15)**2,outer2=(n*.41)**2,margin=10;let ab=0,a2=0,b2=0,count=0;for(let y=margin;y<n-margin;y+=2){const yy=y+dy;if(yy<margin||yy>=n-margin)continue;for(let x=margin;x<n-margin;x+=2){const xx=x+dx;if(xx<margin||xx>=n-margin)continue;const rx=x-c,ry=y-c,rr=rx*rx+ry*ry;if(rr<inner2||rr>outer2)continue;const rxx=xx-c,ryy=yy-c,rr2=rxx*rxx+ryy*ryy;if(rr2<inner2||rr2>outer2)continue;const av=a[y*n+x],bv=b[yy*n+xx];ab+=av*bv;a2+=av*av;b2+=bv*bv;count++}}return count>200&&a2>1&&b2>1?ab/Math.sqrt(a2*b2):-1}
function refine(neg,center,pos){const d=neg-2*center+pos;return!Number.isFinite(d)||Math.abs(d)<1e-6?0:clamp(.5*(neg-pos)/d,-.5,.5)}
function estimateRepresentation(previous,current,dataKey,energyKey,representation){const a=previous[dataKey],b=current[dataKey],energy=current[energyKey];if(!a||!b||!Number.isFinite(energy))return null;const max=7,scores=new Map();let best={score:-1,dx:0,dy:0},second=-1;for(let dy=-max;dy<=max;dy++)for(let dx=-max;dx<=max;dx++){const score=correlation(a,b,WORK,dx,dy);scores.set(`${dx},${dy}`,score);if(score>best.score){second=best.score;best={score,dx,dy}}else if(score>second)second=score}const get=(dx,dy)=>scores.get(`${dx},${dy}`)??best.score,dx=best.dx+(Math.abs(best.dx)<max?refine(get(best.dx-1,best.dy),best.score,get(best.dx+1,best.dy)):0),dy=best.dy+(Math.abs(best.dy)<max?refine(get(best.dx,best.dy-1),best.score,get(best.dx,best.dy+1)):0),texture=clamp((energy-4)/22,0,1),corr=clamp((best.score-.68)/.32,0,1),sharp=clamp((best.score-second)/.025,0,1),confidence=corr*.78+texture*.17+sharp*.05,magnitude=Math.hypot(dx,dy);let reason='';if(best.score<.82)reason=`low-correlation (${best.score.toFixed(3)})`;else if(energy<5.5)reason=`low-texture (${energy.toFixed(2)})`;else if(magnitude>5.5)reason=`motion-outlier (${magnitude.toFixed(2)} work px)`;return{dx,dy,confidence,score:best.score,energy,accepted:!reason,reason,representation}}
function estimate(previous,current){const candidates=[estimateRepresentation(previous,current,'data','energy','adaptive-translucent-map'),estimateRepresentation(previous,current,'rawData','rawEnergy','raw-gradient')].filter(Boolean),accepted=candidates.filter(x=>x.accepted).sort((a,b)=>b.score-a.score);if(accepted.length)return accepted[0];candidates.sort((a,b)=>b.score-a.score);return candidates[0]||{dx:0,dy:0,confidence:0,score:-1,energy:0,accepted:false,reason:'feature-unavailable',representation:'none'}}
function convertedDelta(dx,dy,sourceScale){const playerX=(-dx)*sourceScale,playerY=(-dy)*sourceScale,radians=state.orientation*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians);return{x:(playerX*c-playerY*s)*state.scale,y:(playerX*s+playerY*c)*state.scale}}
function moveMarker(dx,dy,sourceScale){if(!state.manualSeed||!state.marker||!mapRef)return{moved:false,reason:'needs-reseed',needsReseed:true};const corrected=convertedDelta(dx,dy,sourceScale);state.correctedDx=corrected.x;state.correctedDy=corrected.y;if(Math.hypot(corrected.x,corrected.y)<MIN_MARKER_PX)return{moved:false,reason:'no-motion',corrected};const nextX=state.trackingState.currentMapX+corrected.x,nextY=state.trackingState.currentMapY+corrected.y,point=window.L.point(nextX,nextY),latlng=mapRef.unproject(point,TRACKING_REFERENCE_ZOOM),bounds=mapRef.options.maxBounds;if(bounds&&!bounds.contains(latlng))return{moved:false,reason:'out-of-map-bounds',needsReseed:true,corrected};const before=state.marker.getLatLng();state.marker.setLatLng(latlng);const actual=state.marker.getLatLng(),beforePoint=mapRef.project(before,TRACKING_REFERENCE_ZOOM),afterPoint=mapRef.project(actual,TRACKING_REFERENCE_ZOOM),markerPx=Math.hypot(afterPoint.x-beforePoint.x,afterPoint.y-beforePoint.y);state.markerDeltaLat=actual.lat-before.lat;state.markerDeltaLng=actual.lng-before.lng;if(markerPx<MIN_MARKER_PX){state.marker.setLatLng(before);state.markerDeltaLat=0;state.markerDeltaLng=0;return{moved:false,reason:'marker-no-delta',corrected}}state.trackingState.currentMapX=nextX;state.trackingState.currentMapY=nextY;state.trackingState.cumulativeDx+=corrected.x;state.trackingState.cumulativeDy+=corrected.y;return{moved:true,reason:'—',corrected,latlng:actual,markerPx}}
function processFeature(current){if(!current)return{accepted:false,reason:'feature-unavailable'};state.trackingState.frameCount++;state.lastEnergy=current.energy;state.markerDeltaLat=0;state.markerDeltaLng=0;if(!state.manualSeed){state.previous=null;setStatus(STATUS.NEEDS_RESEED,'needsReseed');state.holdReason='needs-reseed';metrics();return{accepted:false,reason:'needs-reseed',status:state.trackingState.status}}if(!state.previous){state.previous=current;state.holdReason='waiting-baseline';setStatus(state.stream?STATUS.TRACKING:STATUS.PAUSED_NO_FRAME,state.stream?'tracking':'paused');metrics();return{accepted:false,baseline:true,reason:'waiting-baseline',energy:current.energy,sourceScale:current.sourceScale,normalization:current.normalization,status:state.trackingState.status,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy}}const motion=estimate(state.previous,current);state.trackingState.confidence=motion.confidence;state.rawDx=motion.dx;state.rawDy=motion.dy;state.lastScore=motion.score;state.lastEnergy=motion.energy;if(!motion.accepted){state.correctedDx=0;state.correctedDy=0;state.held++;state.lowFrames++;state.holdReason=motion.reason;setStatus(STATUS.LOW_CONFIDENCE,'lowConfidence');if(state.lowFrames>=3){state.previous=current;state.lowFrames=0}metrics();return{...motion,sourceScale:current.sourceScale,normalization:current.normalization,moved:false,moveReason:motion.reason,status:state.trackingState.status,convertedDx:0,convertedDy:0,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy,currentMapX:state.trackingState.currentMapX,currentMapY:state.trackingState.currentMapY}}state.previous=current;state.lowFrames=0;const result=moveMarker(motion.dx,motion.dy,current.sourceScale);if(result.needsReseed){state.held++;state.holdReason=result.reason;setStatus(STATUS.NEEDS_RESEED,'needsReseed')}else if(result.moved){state.accepted++;state.holdReason='—';setStatus(STATUS.TRACKING,'tracking')}else{state.holdReason=result.reason;setStatus(STATUS.TRACKING,'tracking')}metrics();return{...motion,sourceScale:current.sourceScale,normalization:current.normalization,moved:result.moved,moveReason:result.reason,markerPx:result.markerPx||0,latlng:result.latlng||state.marker?.getLatLng?.()||null,status:state.trackingState.status,convertedDx:result.corrected?.x||0,convertedDy:result.corrected?.y||0,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy,currentMapX:state.trackingState.currentMapX,currentMapY:state.trackingState.currentMapY}}
function sample(){if(!state.stream||!state.video)return;if(!state.manualSeed){setStatus(STATUS.NEEDS_RESEED,'needsReseed');return}const current=features();if(current)processFeature(current)}
async function start(){if(state.stream)return;if(!navigator.mediaDevices?.getDisplayMedia){setStatus(STATUS.PAUSED_NO_FRAME,'paused');return}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),video=document.createElement('video');video.muted=true;video.playsInline=true;video.srcObject=stream;await video.play();if(!video.videoWidth)await new Promise(resolve=>video.addEventListener('loadedmetadata',resolve,{once:true}));state.stream=stream;state.video=video;state.testReplayStream=false;state.previous=null;state.lowFrames=0;{const unit=Math.min(video.videoWidth,video.videoHeight);state.roiX=unit*.125;state.roiY=unit*.125}resetMotionDiagnostics('capture-ready');stream.getVideoTracks()[0]?.addEventListener('ended',()=>stop('ended'),{once:true});state.previewRaf=requestAnimationFrame(preview);state.timer=setInterval(sample,SAMPLE_MS);refresh();setStatus(state.manualSeed?STATUS.TRACKING:STATUS.NEEDS_RESEED,state.manualSeed?'tracking':'ready');window.dispatchEvent(new CustomEvent('wwmsync:vision:capture-ready',{detail:{width:video.videoWidth,height:video.videoHeight,displaySurface:stream.getVideoTracks()[0]?.getSettings?.().displaySurface||'unknown'}}))}catch(error){console.warn('[WWMSync] Vision capture',error);setStatus(STATUS.PAUSED_NO_FRAME,'paused')}}
function stop(reason='user'){clearMapClick();if(state.timer)clearInterval(state.timer);state.timer=0;if(state.previewRaf)cancelAnimationFrame(state.previewRaf);state.previewRaf=0;const stream=state.stream;state.stream=null;state.testReplayStream=false;if(stream)for(const track of stream.getTracks())if(track.readyState!=='ended')track.stop();if(state.video){state.video.srcObject=null;state.video=null}state.previous=null;state.lowFrames=0;state.trackingState.confidence=0;resetMotionDiagnostics(reason==='ended'?'capture-ended':'stopped');refresh();setStatus(STATUS.PAUSED_NO_FRAME,'paused');window.dispatchEvent(new CustomEvent('wwmsync:vision:capture-stopped',{detail:{reason}}))}
function captureRoiCanvas(size=WORK){if(!state.stream||!state.video?.videoWidth)return null;const n=clamp(Math.round(Number(size)||WORK),64,384),r=roi(state.video),canvas=document.createElement('canvas');canvas.width=n;canvas.height=n;canvas.getContext('2d',{alpha:false,willReadFrequently:true}).drawImage(state.video,r.x,r.y,r.size,r.size,0,0,n,n);return canvas}
function publicState(){return{active:!!state.stream,manualSeed:state.manualSeed?{...state.manualSeed}:null,trackingState:{...state.trackingState},markerLatLng:state.marker?.getLatLng?.()||null,hasSeed:!!state.manualSeed,hasMarker:!!state.marker,referenceZoom:TRACKING_REFERENCE_ZOOM,mapZoom:mapRef?.getZoom?.()??null,scale:state.scale,orientation:state.orientation,status:state.trackingState.status}}
window.__WWMSYNC_VISION_BRIDGE__={captureRoi:captureRoiCanvas,state:publicState,project:(lat,lng,zoom=TRACKING_REFERENCE_ZOOM)=>mapRef?mapRef.project(window.L.latLng(lat,lng),zoom):null};
window.__WWMSYNC_VISION_DIAGNOSTICS__=()=>({rawDx:state.rawDx,rawDy:state.rawDy,correctedDx:state.correctedDx,correctedDy:state.correctedDy,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy,currentMapX:state.trackingState.currentMapX,currentMapY:state.trackingState.currentMapY,confidence:state.trackingState.confidence,frameCount:state.trackingState.frameCount,status:state.trackingState.status,holdReason:state.holdReason,accepted:state.accepted,held:state.held,referenceZoom:TRACKING_REFERENCE_ZOOM,orientation:state.orientation,scale:state.scale,manualSeed:state.manualSeed?{...state.manualSeed}:null,markerLatLng:state.marker?.getLatLng?.()||null,hasSeed:!!state.manualSeed,hasMarker:!!state.marker});
window.__WWMSYNC_VISION_TEST__={featureCanvas:featuresFromCanvas,estimatePair:estimate,transformDelta:(dx,dy,sourceScale=1)=>convertedDelta(Number(dx),Number(dy),Number(sourceScale)),motionStepCanvas:canvas=>processFeature(featuresFromCanvas(canvas)),beginReplay:()=>{if(!state.stream){state.stream={getTracks:()=>[]};state.testReplayStream=true}refresh();setStatus(state.manualSeed?STATUS.TRACKING:STATUS.NEEDS_RESEED,state.manualSeed?'tracking':'ready');return true},setManualSeed:(lat,lng,timestamp=Date.now())=>setManualSeed({lat:Number(lat),lng:Number(lng)},timestamp),armManualSeed:()=>{requestSeed();return!!state.mapClickHandler},resetMotionReference:()=>{state.previous=null;state.lowFrames=0;return true},setTuning:(scale=1,orientation=0)=>{state.scale=clamp(Number(scale),.25,6);state.orientation=clamp(Number(orientation),-180,180);return{scale:state.scale,orientation:state.orientation}},setViewport:(lat,lng,zoom=TRACKING_REFERENCE_ZOOM)=>{if(!mapRef)return false;mapRef.setView([Number(lat),Number(lng)],Number(zoom),{animate:false});return true},mapCenter:()=>mapRef?mapRef.getCenter():null,mapContainerCenterLatLng:()=>mapRef?mapRef.containerPointToLatLng(mapRef.getSize().divideBy(2)):null,clearSeed:()=>{clearSeed('test-clear');return true},endReplay:()=>{if(state.testReplayStream){state.stream=null;state.testReplayStream=false;state.previous=null;refresh();setStatus(STATUS.PAUSED_NO_FRAME,'paused')}return true},state:publicState,constants:{WORK,MIN_MARKER_PX,TRACKING_REFERENCE_ZOOM,ZERO_RAW_EPSILON,ZERO_CUMULATIVE_EPSILON,STATUS}};
window.__WWMSYNC_VISION_HARDENING__={version:'M1_MANUAL_RELATIVE_V1',implementation:'EXISTING_REUSED',normalization:'dual-source-agnostic',absoluteLocalization:false};
el.visionStartButton.addEventListener('click',()=>void start());el.visionStopButton.addEventListener('click',()=>stop('user'));el.visionAnchorButton.addEventListener('click',requestSeed);el.visionPreview.addEventListener('click',selectRoi);el.visionRoiSize.addEventListener('input',()=>{state.roiFraction=clamp(Number(el.visionRoiSize.value),.12,.34);localStorage.setItem(ROI_KEY,String(state.roiFraction));announceRoiChange('roi-size-reset')});el.visionScale.addEventListener('input',()=>{state.scale=clamp(Number(el.visionScale.value),.25,6);localStorage.setItem(SCALE_KEY,String(state.scale));metrics()});el.visionOrientation?.addEventListener('input',()=>{state.orientation=clamp(Number(el.visionOrientation.value),-180,180);localStorage.setItem(ORIENTATION_KEY,String(state.orientation));metrics()});document.getElementById('languageSelect')?.addEventListener('change',()=>queueMicrotask(localize));new MutationObserver(localize).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.addEventListener('beforeunload',()=>{if(state.stream&&!state.testReplayStream)stop('user')});refresh();localize();setStatus(STATUS.PAUSED_NO_FRAME,'off');
})();
