#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
VISION = ROOT / 'vision-sync.js'
source = VISION.read_text(encoding='utf-8')

if "M1_MANUAL_RELATIVE_V1" in source:
    print('M1 manual-relative runtime already applied')
    raise SystemExit(0)

# Preserve the already-hardened frame-to-frame estimator exactly. M1 changes
# product architecture/state plumbing, not the proven representation or gates.
m = re.search(
    r"function visionPercentile\(values,p\)\{.*?\nfunction estimate\(previous,current\)\{.*?\}\nfunction correctedDelta",
    source,
    flags=re.S,
)
if not m:
    raise RuntimeError('Could not locate existing motion estimator block')
estimator = m.group(0).rsplit('\nfunction correctedDelta', 1)[0]
for frozen in ("best.score<.82", "energy<5.5", "magnitude>5.5"):
    if frozen not in estimator:
        raise RuntimeError(f'Frozen motion gate missing: {frozen}')
if "raw-gradient" not in estimator or "dual-source-agnostic" not in estimator:
    raise RuntimeError('Expected REAL_FIXTURE_V2 dual-source motion estimator not found')

runtime = r'''(()=>{
'use strict';
const SCALE_KEY='wwmsync:vision-scale',ROI_KEY='wwmsync:vision-roi',ORIENTATION_KEY='wwmsync:vision-orientation';
const SAMPLE_MS=250,WORK=192,MIN_MARKER_PX=.05,TRACKING_REFERENCE_ZOOM=11;
const ZERO_RAW_EPSILON=0.05,ZERO_CUMULATIVE_EPSILON=0.25;
const STATUS=Object.freeze({TRACKING:'TRACKING',LOW_CONFIDENCE:'LOW_CONFIDENCE',PAUSED_NO_FRAME:'PAUSED_NO_FRAME',NEEDS_RESEED:'NEEDS_RESEED'});
const TEXT={
vi:{title:'Vision Sync',intro:'Chia sẻ cửa sổ GeForce NOW hoặc WWM local client. WWMSync chỉ đọc pixel minimap cục bộ trong tab này; không upload video và không đọc memory/process/file/packet.',start:'Bắt đầu Vision Sync',stop:'Dừng',roiHint:'ROI mặc định ở minimap góc trên-trái. Bấm đúng tâm minimap trong preview nếu cần chỉnh.',anchor:'Đặt vị trí hiện tại',resync:'Đồng bộ lại vị trí',anchorHint:'Bấm nút rồi click đúng vị trí nhân vật hiện tại trên WWMSync map. Vị trí này là mốc tuyệt đối duy nhất; sau đó marker chỉ di chuyển tương đối theo minimap.',confidence:'Tin cậy',accepted:'Frame làm marker di chuyển',held:'Frame giữ',advanced:'Tinh chỉnh',roiSize:'Kích thước ROI',scale:'Tỉ lệ di chuyển',orientation:'Bù hướng minimap',diagnostics:'Motion diagnostics',rawDelta:'Raw terrain dx/dy',correctedDelta:'Converted map dx/dy',cumulative:'Cumulative displacement',markerDelta:'Marker Δ lat/lng',diagConfidence:'Confidence',holdReason:'Tracking state',off:'Vision Sync đang tắt. Vị trí cuối cùng được giữ lại.',ready:'Capture đã sẵn sàng. Hãy đặt vị trí hiện tại trên map để bắt đầu tracking.',clickMap:'Click vị trí hiện tại của nhân vật trên map.',tracking:'Tracking tương đối từ vị trí đã đặt.',lowConfidence:'Frame hiện tại có độ tin cậy thấp; marker được giữ nguyên.',paused:'Không có frame capture; marker giữ nguyên vị trí cuối.',needsReseed:'Cần đặt lại vị trí hiện tại trước khi tiếp tục tracking.',anchorSet:'Đã đặt vị trí. Frame minimap tiếp theo sẽ là baseline mới.',roiSelected:'Đã cập nhật vùng minimap; frame tiếp theo sẽ là baseline mới.'},
en:{title:'Vision Sync',intro:'Share either GeForce NOW or the local WWM client. WWMSync reads minimap pixels locally in this tab only; it does not upload video or read memory/process/files/packets.',start:'Start Vision Sync',stop:'Stop',roiHint:'The default ROI targets the upper-left minimap. Click the minimap center in the preview if needed.',anchor:'Set current position',resync:'Re-sync position',anchorHint:'Click the button, then click your actual player position on the WWMSync map. That manual seed is the only absolute position; subsequent marker updates are relative minimap motion only.',confidence:'Confidence',accepted:'Frames moving marker',held:'Held frames',advanced:'Tuning',roiSize:'ROI size',scale:'Movement scale',orientation:'Minimap orientation',diagnostics:'Motion diagnostics',rawDelta:'Raw terrain dx/dy',correctedDelta:'Converted map dx/dy',cumulative:'Cumulative displacement',markerDelta:'Marker Δ lat/lng',diagConfidence:'Confidence',holdReason:'Tracking state',off:'Vision Sync is off. The last marker position is retained.',ready:'Capture is ready. Set your current map position to begin tracking.',clickMap:'Click your current character position on the map.',tracking:'Tracking relative motion from the manual seed.',lowConfidence:'Current frame confidence is low; marker position is held.',paused:'No capture frame is available; the last marker position is held.',needsReseed:'Set your current position again before tracking can continue.',anchorSet:'Position set. The next minimap frame becomes the new baseline.',roiSelected:'Minimap region updated; the next frame becomes the new baseline.'}
};
const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
const loadNumber=(key,fallback,min,max)=>{const raw=localStorage.getItem(key);if(raw===null||raw==='')return fallback;const v=Number(raw);return Number.isFinite(v)?clamp(v,min,max):fallback};
const freshTracking=()=>({currentMapX:null,currentMapY:null,cumulativeDx:0,cumulativeDy:0,confidence:0,frameCount:0,status:STATUS.PAUSED_NO_FRAME});
const state={stream:null,video:null,previewRaf:0,timer:0,workCanvas:null,workCtx:null,roiX:null,roiY:null,roiFraction:loadNumber(ROI_KEY,.25,.12,.34),scale:loadNumber(SCALE_KEY,1,.25,6),orientation:loadNumber(ORIENTATION_KEY,0,-180,180),previous:null,manualSeed:null,trackingState:freshTracking(),marker:null,mapClickHandler:null,accepted:0,held:0,lowFrames:0,rawDx:0,rawDy:0,correctedDx:0,correctedDy:0,markerDeltaLat:0,markerDeltaLng:0,holdReason:'—',lastScore:0,lastEnergy:0,statusKey:'off',testReplayStream:false};
let mapRef=null;
const ids=['visionStartButton','visionStopButton','visionAnchorButton','visionBadge','visionStatus','visionPreview','visionSetup','visionConfidence','visionAccepted','visionHeld','visionRoiSize','visionRoiValue','visionScale','visionScaleValue','visionOrientation','visionOrientationValue','visionRawDelta','visionCorrectedDelta','visionCumulative','visionMarkerDelta','visionDiagnosticConfidence','visionHoldReason','sidebar'];
const el=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const lang=()=>document.documentElement.lang==='en'||document.getElementById('languageSelect')?.value==='en'?'en':'vi',tx=key=>TEXT[lang()][key]||TEXT.en[key]||key,fmt=v=>Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(3)}`:'—';
function statusClass(status){return status===STATUS.TRACKING?'good':status===STATUS.LOW_CONFIDENCE||status===STATUS.NEEDS_RESEED?'warn':''}
function statusLabel(status){return status===STATUS.PAUSED_NO_FRAME?'PAUSED':status}
function setStatus(status,key){state.trackingState.status=status;state.statusKey=key;if(!el.visionBadge||!el.visionStatus)return;el.visionBadge.textContent=statusLabel(status);el.visionBadge.className=`status-badge ${statusClass(status)}`.trim();el.visionStatus.textContent=tx(key);el.visionStatus.className=`vision-status ${statusClass(status)}`.trim()}
function refreshAnchorLabel(){if(el.visionAnchorButton)el.visionAnchorButton.textContent=tx(state.manualSeed?'resync':'anchor')}
function metrics(){if(el.visionConfidence)el.visionConfidence.textContent=`${Math.round(clamp(state.trackingState.confidence,0,1)*100)}%`;if(el.visionAccepted)el.visionAccepted.textContent=String(state.accepted);if(el.visionHeld)el.visionHeld.textContent=String(state.held);if(el.visionRoiValue)el.visionRoiValue.textContent=`${Math.round(state.roiFraction*100)}%`;if(el.visionScaleValue)el.visionScaleValue.textContent=`${state.scale.toFixed(2)}×`;if(el.visionOrientationValue)el.visionOrientationValue.textContent=`${Math.round(state.orientation)}°`;if(el.visionRawDelta)el.visionRawDelta.textContent=`${fmt(state.rawDx)}, ${fmt(state.rawDy)} work px`;if(el.visionCorrectedDelta)el.visionCorrectedDelta.textContent=`${fmt(state.correctedDx)}, ${fmt(state.correctedDy)} map px`;if(el.visionCumulative)el.visionCumulative.textContent=`${fmt(state.trackingState.cumulativeDx)}, ${fmt(state.trackingState.cumulativeDy)} map px`;if(el.visionMarkerDelta)el.visionMarkerDelta.textContent=`${fmt(state.markerDeltaLat)}, ${fmt(state.markerDeltaLng)}`;if(el.visionDiagnosticConfidence)el.visionDiagnosticConfidence.textContent=`${Math.round(clamp(state.trackingState.confidence,0,1)*100)}% · corr ${state.lastScore.toFixed(3)} · energy ${state.lastEnergy.toFixed(2)}`;if(el.visionHoldReason)el.visionHoldReason.textContent=`${state.trackingState.status} · ${state.holdReason||'—'}`}
function localize(){document.querySelectorAll('[data-vision-i18n]').forEach(node=>{const key=node.dataset.visionI18n;if(key==='anchor')refreshAnchorLabel();else node.textContent=tx(key)});setStatus(state.trackingState.status,state.statusKey);refreshAnchorLabel();metrics()}
function refresh(){const active=!!state.stream;el.visionStartButton.disabled=active;el.visionStopButton.disabled=!active;el.visionAnchorButton.disabled=!active||!mapRef;el.visionSetup.classList.toggle('hidden',!active);el.visionRoiSize.value=String(state.roiFraction);el.visionScale.value=String(state.scale);if(el.visionOrientation)el.visionOrientation.value=String(state.orientation);refreshAnchorLabel();metrics()}
function clearMapClick(){if(state.mapClickHandler&&mapRef)mapRef.off('click',state.mapClickHandler);state.mapClickHandler=null;el.visionAnchorButton.classList.remove('armed')}
function resetMotionDiagnostics(reason='—'){state.rawDx=0;state.rawDy=0;state.correctedDx=0;state.correctedDy=0;state.markerDeltaLat=0;state.markerDeltaLng=0;state.holdReason=reason;state.lastScore=0;state.lastEnergy=0}
function clearSeed(reason='needs-reseed'){clearMapClick();if(state.marker){state.marker.remove();state.marker=null}state.manualSeed=null;state.previous=null;state.accepted=0;state.held=0;state.lowFrames=0;state.trackingState=freshTracking();resetMotionDiagnostics(reason);setStatus(state.stream?STATUS.NEEDS_RESEED:STATUS.PAUSED_NO_FRAME,state.stream?'needsReseed':'paused');refresh()}
function attachMap(map){mapRef=map;map.once('unload',()=>{if(mapRef===map){if(state.marker){state.marker.remove();state.marker=null}state.manualSeed=null;state.previous=null;state.trackingState=freshTracking();mapRef=null;setStatus(state.stream?STATUS.NEEDS_RESEED:STATUS.PAUSED_NO_FRAME,state.stream?'needsReseed':'paused');refresh();window.dispatchEvent(new CustomEvent('wwmsync:vision:map-unloaded'))}});refresh();window.dispatchEvent(new CustomEvent('wwmsync:vision:map-ready'))}
if(window.L?.map){const original=window.L.map;window.L.map=function(...args){const map=original.apply(this,args);attachMap(map);return map}}
function markerAt(latlng){if(!mapRef)return false;if(state.marker)state.marker.setLatLng(latlng);else{const icon=window.L.divIcon({className:'vision-player-marker-wrap',html:'<div class="vision-player-marker"><span></span></div>',iconSize:[24,24],iconAnchor:[12,12]});state.marker=window.L.marker(latlng,{icon,interactive:false,zIndexOffset:1200}).addTo(mapRef)}return true}
function setManualSeed(latlng,timestamp=Date.now()){if(!mapRef)return{ok:false,reason:'map-unavailable'};const ll=window.L.latLng(Number(latlng.lat),Number(latlng.lng)),bounds=mapRef.options.maxBounds;if(!Number.isFinite(ll.lat)||!Number.isFinite(ll.lng))return{ok:false,reason:'invalid-latlng'};if(bounds&&!bounds.contains(ll))return{ok:false,reason:'out-of-map-bounds'};const p=mapRef.project(ll,TRACKING_REFERENCE_ZOOM);state.manualSeed={mapX:p.x,mapY:p.y,timestamp:Number(timestamp)||Date.now()};state.trackingState={currentMapX:p.x,currentMapY:p.y,cumulativeDx:0,cumulativeDy:0,confidence:0,frameCount:0,status:state.stream?STATUS.TRACKING:STATUS.PAUSED_NO_FRAME};state.previous=null;state.accepted=0;state.held=0;state.lowFrames=0;resetMotionDiagnostics('manual-seed');markerAt(ll);setStatus(state.trackingState.status,state.stream?'anchorSet':'paused');refresh();const detail={manualSeed:{...state.manualSeed},lat:ll.lat,lng:ll.lng};window.dispatchEvent(new CustomEvent('wwmsync:vision:manual-seed',{detail}));return{ok:true,...detail}}
function requestSeed(){if(!state.stream||!mapRef)return;clearMapClick();el.visionAnchorButton.classList.add('armed');setStatus(STATUS.NEEDS_RESEED,'clickMap');if(innerWidth<=800)el.sidebar?.classList.remove('open');const map=mapRef,handler=event=>{map.off('click',handler);state.mapClickHandler=null;el.visionAnchorButton.classList.remove('armed');const result=setManualSeed(event.latlng);if(!result.ok)setStatus(STATUS.NEEDS_RESEED,'needsReseed')};state.mapClickHandler=handler;map.on('click',handler)}
function roi(video){const unit=Math.min(video.videoWidth,video.videoHeight),size=unit*state.roiFraction,half=size/2,defaultCenter=unit*.125,cx=clamp(state.roiX??defaultCenter,half,video.videoWidth-half),cy=clamp(state.roiY??defaultCenter,half,video.videoHeight-half);state.roiX=cx;state.roiY=cy;return{x:cx-half,y:cy-half,size}}
function preview(){const video=state.video,canvas=el.visionPreview;if(!video||!state.stream)return;const width=360,height=Math.max(160,Math.round(width*video.videoHeight/video.videoWidth));if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}const ctx=canvas.getContext('2d',{alpha:false});ctx.drawImage(video,0,0,width,height);const r=roi(video),sx=width/video.videoWidth,sy=height/video.videoHeight;ctx.save();ctx.strokeStyle='#f2cc7a';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.strokeRect(r.x*sx,r.y*sy,r.size*sx,r.size*sy);ctx.restore();state.previewRaf=requestAnimationFrame(preview)}
function announceRoiChange(reason){state.previous=null;state.lowFrames=0;state.holdReason=reason;state.markerDeltaLat=0;state.markerDeltaLng=0;if(state.manualSeed)setStatus(state.stream?STATUS.TRACKING:STATUS.PAUSED_NO_FRAME,state.stream?'roiSelected':'paused');else setStatus(state.stream?STATUS.NEEDS_RESEED:STATUS.PAUSED_NO_FRAME,state.stream?'needsReseed':'paused');window.dispatchEvent(new CustomEvent('wwmsync:vision:roi-ready',{detail:{reason}}));metrics()}
function selectRoi(event){if(!state.video||!state.stream)return;const rect=el.visionPreview.getBoundingClientRect();state.roiX=clamp((event.clientX-rect.left)/rect.width,0,1)*state.video.videoWidth;state.roiY=clamp((event.clientY-rect.top)/rect.height,0,1)*state.video.videoHeight;announceRoiChange('roi-baseline-reset')}
__ESTIMATOR_BLOCK__
function convertedDelta(dx,dy,sourceScale){const playerX=(-dx)*sourceScale,playerY=(-dy)*sourceScale,radians=state.orientation*Math.PI/180,c=Math.cos(radians),s=Math.sin(radians);return{x:(playerX*c-playerY*s)*state.scale,y:(playerX*s+playerY*c)*state.scale}}
function moveMarker(dx,dy,sourceScale){if(!state.manualSeed||!state.marker||!mapRef)return{moved:false,reason:'needs-reseed',needsReseed:true};const corrected=convertedDelta(dx,dy,sourceScale);state.correctedDx=corrected.x;state.correctedDy=corrected.y;if(Math.hypot(corrected.x,corrected.y)<MIN_MARKER_PX)return{moved:false,reason:'no-motion',corrected};const nextX=state.trackingState.currentMapX+corrected.x,nextY=state.trackingState.currentMapY+corrected.y,point=window.L.point(nextX,nextY),latlng=mapRef.unproject(point,TRACKING_REFERENCE_ZOOM),bounds=mapRef.options.maxBounds;if(bounds&&!bounds.contains(latlng))return{moved:false,reason:'out-of-map-bounds',needsReseed:true,corrected};const before=state.marker.getLatLng();state.marker.setLatLng(latlng);const actual=state.marker.getLatLng(),beforePoint=mapRef.project(before,TRACKING_REFERENCE_ZOOM),afterPoint=mapRef.project(actual,TRACKING_REFERENCE_ZOOM),markerPx=Math.hypot(afterPoint.x-beforePoint.x,afterPoint.y-beforePoint.y);state.markerDeltaLat=actual.lat-before.lat;state.markerDeltaLng=actual.lng-before.lng;if(markerPx<MIN_MARKER_PX){state.marker.setLatLng(before);state.markerDeltaLat=0;state.markerDeltaLng=0;return{moved:false,reason:'marker-no-delta',corrected}}state.trackingState.currentMapX=nextX;state.trackingState.currentMapY=nextY;state.trackingState.cumulativeDx+=corrected.x;state.trackingState.cumulativeDy+=corrected.y;return{moved:true,reason:'—',corrected,latlng:actual,markerPx}}
function processFeature(current){if(!current)return{accepted:false,reason:'feature-unavailable'};state.trackingState.frameCount++;state.lastEnergy=current.energy;state.markerDeltaLat=0;state.markerDeltaLng=0;if(!state.manualSeed){state.previous=null;setStatus(STATUS.NEEDS_RESEED,'needsReseed');state.holdReason='needs-reseed';metrics();return{accepted:false,reason:'needs-reseed',status:state.trackingState.status}}if(!state.previous){state.previous=current;state.holdReason='waiting-baseline';setStatus(state.stream?STATUS.TRACKING:STATUS.PAUSED_NO_FRAME,state.stream?'tracking':'paused');metrics();return{accepted:false,baseline:true,reason:'waiting-baseline',energy:current.energy,sourceScale:current.sourceScale,normalization:current.normalization,status:state.trackingState.status,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy}}const motion=estimate(state.previous,current);state.trackingState.confidence=motion.confidence;state.rawDx=motion.dx;state.rawDy=motion.dy;state.lastScore=motion.score;state.lastEnergy=motion.energy;if(!motion.accepted){state.correctedDx=0;state.correctedDy=0;state.held++;state.lowFrames++;state.holdReason=motion.reason;setStatus(STATUS.LOW_CONFIDENCE,'lowConfidence');if(state.lowFrames>=3){state.previous=current;state.lowFrames=0}metrics();return{...motion,sourceScale:current.sourceScale,normalization:current.normalization,moved:false,moveReason:motion.reason,status:state.trackingState.status,convertedDx:0,convertedDy:0,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy,currentMapX:state.trackingState.currentMapX,currentMapY:state.trackingState.currentMapY}}state.previous=current;state.lowFrames=0;const result=moveMarker(motion.dx,motion.dy,current.sourceScale);if(result.needsReseed){state.held++;state.holdReason=result.reason;setStatus(STATUS.NEEDS_RESEED,'needsReseed')}else if(result.moved){state.accepted++;state.holdReason='—';setStatus(STATUS.TRACKING,'tracking')}else{state.holdReason=result.reason;setStatus(STATUS.TRACKING,'tracking')}metrics();return{...motion,sourceScale:current.sourceScale,normalization:current.normalization,moved:result.moved,moveReason:result.reason,markerPx:result.markerPx||0,latlng:result.latlng||state.marker?.getLatLng?.()||null,status:state.trackingState.status,convertedDx:result.corrected?.x||0,convertedDy:result.corrected?.y||0,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy,currentMapX:state.trackingState.currentMapX,currentMapY:state.trackingState.currentMapY}}
function sample(){if(!state.stream||!state.video)return;if(!state.manualSeed){setStatus(STATUS.NEEDS_RESEED,'needsReseed');return}const current=features();if(current)processFeature(current)}
async function start(){if(state.stream)return;if(!navigator.mediaDevices?.getDisplayMedia){setStatus(STATUS.PAUSED_NO_FRAME,'paused');return}try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}),video=document.createElement('video');video.muted=true;video.playsInline=true;video.srcObject=stream;await video.play();if(!video.videoWidth)await new Promise(resolve=>video.addEventListener('loadedmetadata',resolve,{once:true}));state.stream=stream;state.video=video;state.testReplayStream=false;state.previous=null;state.lowFrames=0;{const unit=Math.min(video.videoWidth,video.videoHeight);state.roiX=unit*.125;state.roiY=unit*.125}resetMotionDiagnostics('capture-ready');stream.getVideoTracks()[0]?.addEventListener('ended',()=>stop('ended'),{once:true});state.previewRaf=requestAnimationFrame(preview);state.timer=setInterval(sample,SAMPLE_MS);refresh();setStatus(state.manualSeed?STATUS.TRACKING:STATUS.NEEDS_RESEED,state.manualSeed?'tracking':'ready');window.dispatchEvent(new CustomEvent('wwmsync:vision:capture-ready',{detail:{width:video.videoWidth,height:video.videoHeight,displaySurface:stream.getVideoTracks()[0]?.getSettings?.().displaySurface||'unknown'}}))}catch(error){console.warn('[WWMSync] Vision capture',error);setStatus(STATUS.PAUSED_NO_FRAME,'paused')}}
function stop(reason='user'){clearMapClick();if(state.timer)clearInterval(state.timer);state.timer=0;if(state.previewRaf)cancelAnimationFrame(state.previewRaf);state.previewRaf=0;const stream=state.stream;state.stream=null;state.testReplayStream=false;if(stream)for(const track of stream.getTracks())if(track.readyState!=='ended')track.stop();if(state.video){state.video.srcObject=null;state.video=null}state.previous=null;state.lowFrames=0;state.trackingState.confidence=0;resetMotionDiagnostics(reason==='ended'?'capture-ended':'stopped');refresh();setStatus(STATUS.PAUSED_NO_FRAME,'paused');window.dispatchEvent(new CustomEvent('wwmsync:vision:capture-stopped',{detail:{reason}}))}
function captureRoiCanvas(size=WORK){if(!state.stream||!state.video?.videoWidth)return null;const n=clamp(Math.round(Number(size)||WORK),64,384),r=roi(state.video),canvas=document.createElement('canvas');canvas.width=n;canvas.height=n;canvas.getContext('2d',{alpha:false,willReadFrequently:true}).drawImage(state.video,r.x,r.y,r.size,r.size,0,0,n,n);return canvas}
function publicState(){return{active:!!state.stream,manualSeed:state.manualSeed?{...state.manualSeed}:null,trackingState:{...state.trackingState},markerLatLng:state.marker?.getLatLng?.()||null,hasSeed:!!state.manualSeed,hasMarker:!!state.marker,referenceZoom:TRACKING_REFERENCE_ZOOM,mapZoom:mapRef?.getZoom?.()??null,scale:state.scale,orientation:state.orientation,status:state.trackingState.status}}
window.__WWMSYNC_VISION_BRIDGE__={captureRoi:captureRoiCanvas,state:publicState,project:(lat,lng,zoom=TRACKING_REFERENCE_ZOOM)=>mapRef?mapRef.project(window.L.latLng(lat,lng),zoom):null};
window.__WWMSYNC_VISION_DIAGNOSTICS__=()=>({rawDx:state.rawDx,rawDy:state.rawDy,correctedDx:state.correctedDx,correctedDy:state.correctedDy,cumulativeDx:state.trackingState.cumulativeDx,cumulativeDy:state.trackingState.cumulativeDy,currentMapX:state.trackingState.currentMapX,currentMapY:state.trackingState.currentMapY,confidence:state.trackingState.confidence,frameCount:state.trackingState.frameCount,status:state.trackingState.status,holdReason:state.holdReason,accepted:state.accepted,held:state.held,referenceZoom:TRACKING_REFERENCE_ZOOM,orientation:state.orientation,scale:state.scale,manualSeed:state.manualSeed?{...state.manualSeed}:null,markerLatLng:state.marker?.getLatLng?.()||null,hasSeed:!!state.manualSeed,hasMarker:!!state.marker});
window.__WWMSYNC_VISION_TEST__={featureCanvas:featuresFromCanvas,estimatePair:estimate,transformDelta:(dx,dy,sourceScale=1)=>convertedDelta(Number(dx),Number(dy),Number(sourceScale)),motionStepCanvas:canvas=>processFeature(featuresFromCanvas(canvas)),beginReplay:()=>{if(!state.stream){state.stream={getTracks:()=>[]};state.testReplayStream=true}refresh();setStatus(state.manualSeed?STATUS.TRACKING:STATUS.NEEDS_RESEED,state.manualSeed?'tracking':'ready');return true},setManualSeed:(lat,lng,timestamp=Date.now())=>setManualSeed({lat:Number(lat),lng:Number(lng)},timestamp),armManualSeed:()=>{requestSeed();return!!state.mapClickHandler},resetMotionReference:()=>{state.previous=null;state.lowFrames=0;return true},setTuning:(scale=1,orientation=0)=>{state.scale=clamp(Number(scale),.25,6);state.orientation=clamp(Number(orientation),-180,180);return{scale:state.scale,orientation:state.orientation}},setViewport:(lat,lng,zoom=TRACKING_REFERENCE_ZOOM)=>{if(!mapRef)return false;mapRef.setView([Number(lat),Number(lng)],Number(zoom),{animate:false});return true},mapCenter:()=>mapRef?mapRef.getCenter():null,mapContainerCenterLatLng:()=>mapRef?mapRef.containerPointToLatLng(mapRef.getSize().divideBy(2)):null,clearSeed:()=>{clearSeed('test-clear');return true},endReplay:()=>{if(state.testReplayStream){state.stream=null;state.testReplayStream=false;state.previous=null;refresh();setStatus(STATUS.PAUSED_NO_FRAME,'paused')}return true},state:publicState,constants:{WORK,MIN_MARKER_PX,TRACKING_REFERENCE_ZOOM,ZERO_RAW_EPSILON,ZERO_CUMULATIVE_EPSILON,STATUS}};
window.__WWMSYNC_VISION_HARDENING__={version:'M1_MANUAL_RELATIVE_V1',implementation:'EXISTING_REUSED',normalization:'dual-source-agnostic',absoluteLocalization:false};
el.visionStartButton.addEventListener('click',()=>void start());el.visionStopButton.addEventListener('click',()=>stop('user'));el.visionAnchorButton.addEventListener('click',requestSeed);el.visionPreview.addEventListener('click',selectRoi);el.visionRoiSize.addEventListener('input',()=>{state.roiFraction=clamp(Number(el.visionRoiSize.value),.12,.34);localStorage.setItem(ROI_KEY,String(state.roiFraction));announceRoiChange('roi-size-reset')});el.visionScale.addEventListener('input',()=>{state.scale=clamp(Number(el.visionScale.value),.25,6);localStorage.setItem(SCALE_KEY,String(state.scale));metrics()});el.visionOrientation?.addEventListener('input',()=>{state.orientation=clamp(Number(el.visionOrientation.value),-180,180);localStorage.setItem(ORIENTATION_KEY,String(state.orientation));metrics()});document.getElementById('languageSelect')?.addEventListener('change',()=>queueMicrotask(localize));new MutationObserver(localize).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});window.addEventListener('beforeunload',()=>{if(state.stream&&!state.testReplayStream)stop('user')});refresh();localize();setStatus(STATUS.PAUSED_NO_FRAME,'off');
})();
'''
runtime = runtime.replace('__ESTIMATOR_BLOCK__', estimator)

# Product runtime is M1-only. Historical matcher research remains in git history,
# audit docs and replay tooling; it is not loaded or callable by the product mode.
VISION.write_text(runtime, encoding='utf-8')
print('Applied M1 manual-seed + relative-motion runtime.')
print('MOTION_SOURCE=EXISTING_REUSED')
