#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'vision-sync.js'
s=P.read_text(encoding='utf-8')
if 'REAL_FIXTURE_V2_DUAL_MOTION' in s:
    print('dual motion already applied'); raise SystemExit(0)
old="""function featureFromWorkCanvas(sourceScale){const ctx=state.workCtx,n=WORK,rgba=ctx.getImageData(0,0,n,n).data,gray=new Float32Array(n*n),sample=[],feature=new Float32Array(n*n),c=(n-1)/2,inner2=(n*.13)**2,outer2=(n*.43)**2;for(let i=0,p=0;i<gray.length;i++,p+=4)gray[i]=rgba[p]*.299+rgba[p+1]*.587+rgba[p+2]*.114;for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const rx=x-c,ry=y-c,r2=rx*rx+ry*ry;if(r2>=inner2&&r2<=outer2)sample.push(gray[y*n+x])}const threshold=clamp(visionPercentile(sample,.96),150,195),signal=new Float32Array(n*n);for(let i=0;i<signal.length;i++)signal[i]=clamp((gray[i]-threshold)/25,0,1)*255;const stable=visionGaussianBlur(signal,n);let energy=0,count=0;for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const rx=x-c,ry=y-c,r2=rx*rx+ry*ry;if(r2<inner2||r2>outer2)continue;const i=y*n+x,gx=stable[i+1]-stable[i-1],gy=stable[i+n]-stable[i-n],v=gx+gy*.7;feature[i]=v;energy+=v*v;count++}return{data:feature,energy:count?Math.sqrt(energy/count):0,sourceScale,normalization:{kind:'adaptive-translucent-map',threshold}}}"""
new="""function featureFromWorkCanvas(sourceScale){const ctx=state.workCtx,n=WORK,rgba=ctx.getImageData(0,0,n,n).data,gray=new Float32Array(n*n),sample=[],feature=new Float32Array(n*n),rawData=new Float32Array(n*n),c=(n-1)/2,inner2=(n*.13)**2,outer2=(n*.43)**2;for(let i=0,p=0;i<gray.length;i++,p+=4)gray[i]=rgba[p]*.299+rgba[p+1]*.587+rgba[p+2]*.114;for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const rx=x-c,ry=y-c,r2=rx*rx+ry*ry;if(r2>=inner2&&r2<=outer2)sample.push(gray[y*n+x])}const threshold=clamp(visionPercentile(sample,.96),150,195),signal=new Float32Array(n*n);for(let i=0;i<signal.length;i++)signal[i]=clamp((gray[i]-threshold)/25,0,1)*255;const stable=visionGaussianBlur(signal,n);let energy=0,rawEnergy=0,count=0;for(let y=2;y<n-2;y++)for(let x=2;x<n-2;x++){const rx=x-c,ry=y-c,r2=rx*rx+ry*ry;if(r2<inner2||r2>outer2)continue;const i=y*n+x,gx=stable[i+1]-stable[i-1],gy=stable[i+n]-stable[i-n],v=gx+gy*.7,rgx=gray[i+1]-gray[i-1],rgy=gray[i+n]-gray[i-n],rv=rgx+rgy*.7;feature[i]=v;rawData[i]=rv;energy+=v*v;rawEnergy+=rv*rv;count++}return{data:feature,energy:count?Math.sqrt(energy/count):0,rawData,rawEnergy:count?Math.sqrt(rawEnergy/count):0,sourceScale,normalization:{kind:'dual-source-agnostic',threshold}}}"""
if s.count(old)!=1: raise RuntimeError('featureFromWorkCanvas signature mismatch')
s=s.replace(old,new,1)
old2="""function estimate(previous,current){const max=7,scores=new Map();let best={score:-1,dx:0,dy:0},second=-1;for(let dy=-max;dy<=max;dy++)for(let dx=-max;dx<=max;dx++){const score=correlation(previous.data,current.data,WORK,dx,dy);scores.set(`${dx},${dy}`,score);if(score>best.score){second=best.score;best={score,dx,dy}}else if(score>second)second=score}const get=(dx,dy)=>scores.get(`${dx},${dy}`)??best.score,dx=best.dx+(Math.abs(best.dx)<max?refine(get(best.dx-1,best.dy),best.score,get(best.dx+1,best.dy)):0),dy=best.dy+(Math.abs(best.dy)<max?refine(get(best.dx,best.dy-1),best.score,get(best.dx,best.dy+1)):0),texture=clamp((current.energy-4)/22,0,1),corr=clamp((best.score-.68)/.32,0,1),sharp=clamp((best.score-second)/.025,0,1),confidence=corr*.78+texture*.17+sharp*.05,magnitude=Math.hypot(dx,dy);let reason='';if(best.score<.82)reason=`low-correlation (${best.score.toFixed(3)})`;else if(current.energy<5.5)reason=`low-texture (${current.energy.toFixed(2)})`;else if(magnitude>5.5)reason=`motion-outlier (${magnitude.toFixed(2)} work px)`;return{dx,dy,confidence,score:best.score,energy:current.energy,accepted:!reason,reason}}"""
new2="""function estimateRepresentation(previous,current,dataKey,energyKey,representation){const a=previous[dataKey],b=current[dataKey],energy=current[energyKey];if(!a||!b||!Number.isFinite(energy))return null;const max=7,scores=new Map();let best={score:-1,dx:0,dy:0},second=-1;for(let dy=-max;dy<=max;dy++)for(let dx=-max;dx<=max;dx++){const score=correlation(a,b,WORK,dx,dy);scores.set(`${dx},${dy}`,score);if(score>best.score){second=best.score;best={score,dx,dy}}else if(score>second)second=score}const get=(dx,dy)=>scores.get(`${dx},${dy}`)??best.score,dx=best.dx+(Math.abs(best.dx)<max?refine(get(best.dx-1,best.dy),best.score,get(best.dx+1,best.dy)):0),dy=best.dy+(Math.abs(best.dy)<max?refine(get(best.dx,best.dy-1),best.score,get(best.dx,best.dy+1)):0),texture=clamp((energy-4)/22,0,1),corr=clamp((best.score-.68)/.32,0,1),sharp=clamp((best.score-second)/.025,0,1),confidence=corr*.78+texture*.17+sharp*.05,magnitude=Math.hypot(dx,dy);let reason='';if(best.score<.82)reason=`low-correlation (${best.score.toFixed(3)})`;else if(energy<5.5)reason=`low-texture (${energy.toFixed(2)})`;else if(magnitude>5.5)reason=`motion-outlier (${magnitude.toFixed(2)} work px)`;return{dx,dy,confidence,score:best.score,energy,accepted:!reason,reason,representation}}
function estimate(previous,current){const candidates=[estimateRepresentation(previous,current,'data','energy','adaptive-translucent-map'),estimateRepresentation(previous,current,'rawData','rawEnergy','raw-gradient')].filter(Boolean),accepted=candidates.filter(x=>x.accepted).sort((a,b)=>b.score-a.score);if(accepted.length)return accepted[0];candidates.sort((a,b)=>b.score-a.score);return candidates[0]||{dx:0,dy:0,confidence:0,score:-1,energy:0,accepted:false,reason:'feature-unavailable',representation:'none'}}"""
if s.count(old2)!=1: raise RuntimeError('estimate signature mismatch')
s=s.replace(old2,new2,1)
old3="window.__WWMSYNC_VISION_HARDENING__={version:'REAL_FIXTURE_V1',implementation:'REAL_FIXTURE_V1_DIRECT',normalization:'adaptive-translucent-map'};"
new3="window.__WWMSYNC_VISION_HARDENING__={version:'REAL_FIXTURE_V2',implementation:'REAL_FIXTURE_V2_DUAL_MOTION',normalization:'dual-source-agnostic'};"
if s.count(old3)!=1: raise RuntimeError('hardening marker mismatch')
s=s.replace(old3,new3,1)
P.write_text(s,encoding='utf-8')
print('Applied REAL_FIXTURE_V2_DUAL_MOTION without changing motion gates.')
